name: Deploy React App to S3

on:
  push:
    branches:
      - main  # or 'production', if that's your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Inject environment variables
        run: |
          echo "NEXT_PUBLIC_REGION=$NEXT_PUBLIC_REGION" >> .env
          echo "NEXT_PUBLIC_USER_POOL_ID=$NEXT_PUBLIC_USER_POOL_ID" >> .env
          echo "NEXT_PUBLIC_USER_POOL_WEB_CLIENT_ID=$NEXT_PUBLIC_USER_POOL_WEB_CLIENT_ID" >> .env
          echo "NEXT_PUBLIC_CLIENT_ID=$NEXT_PUBLIC_CLIENT_ID" >> .env
          echo "NEXT_PUBLIC_REDIRECT_URI=$NEXT_PUBLIC_REDIRECT_URI" >> .env
          echo "NEXT_PUBLIC_RESPONSE_TYPE=$NEXT_PUBLIC_RESPONSE_TYPE" >> .env
          echo "NEXT_PUBLIC_SCOPE=$NEXT_PUBLIC_SCOPE" >> .env
        env:
          NEXT_PUBLIC_REGION: ${{ secrets.AWS_REGION }}
          NEXT_PUBLIC_USER_POOL_ID: ${{ secrets.AWS_USER_POOL_ID }}
          NEXT_PUBLIC_CLIENT_ID: ${{ secrets.AWS_CLIENT_ID }}
          NEXT_PUBLIC_REDIRECT_URI: ${{ secrets.AWS_REDIRECT_URI }}
          NEXT_PUBLIC_RESPONSE_TYPE: ${{ secrets.AWS_RESPONSE_TYPE }}
          NEXT_PUBLIC_SCOPE: ${{ secrets.AWS_SCOPE }}

      - name: Build React App
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ./out